Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/cava-resources/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
osb_ctd_nc_file = data_dir / "rca/ctd/osb_ctd_jan2019_1min.nc"
ds_CTD = xr.open_dataset(osb_ctd_nc_file)
ds_CTD
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/xarray/backends/file_manager.py[0m in [0;36m_acquire_with_cache_info[0;34m(self, needs_lock)[0m
[1;32m    198[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 199[0;31m                 [0mfile[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_cache[0m[0;34m[[0m[0mself[0m[0;34m.[0m[0m_key[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    200[0m             [0;32mexcept[0m [0mKeyError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/xarray/backends/lru_cache.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m     52[0m         [0;32mwith[0m [0mself[0m[0;34m.[0m[0m_lock[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 53[0;31m             [0mvalue[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_cache[0m[0;34m[[0m[0mkey[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     54[0m             [0mself[0m[0;34m.[0m[0m_cache[0m[0;34m.[0m[0mmove_to_end[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: [<function _open_scipy_netcdf at 0x7f98530063a0>, ('/home/runner/work/resources/resources/book/_static/data/rca/ctd/osb_ctd_jan2019_1min.nc',), 'r', (('mmap', None), ('version', 2))]

During handling of the above exception, another exception occurred:

[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/xarray/backends/scipy_.py[0m in [0;36m_open_scipy_netcdf[0;34m(filename, mode, mmap, version)[0m
[1;32m     93[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 94[0;31m         [0;32mreturn[0m [0mscipy[0m[0;34m.[0m[0mio[0m[0;34m.[0m[0mnetcdf_file[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0mmode[0m[0;34m,[0m [0mmmap[0m[0;34m=[0m[0mmmap[0m[0;34m,[0m [0mversion[0m[0;34m=[0m[0mversion[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     95[0m     [0;32mexcept[0m [0mTypeError[0m [0;32mas[0m [0me[0m[0;34m:[0m  [0;31m# netcdf3 message is obscure in this case[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/scipy/io/netcdf.py[0m in [0;36m__init__[0;34m(self, filename, mode, mmap, version, maskandscale)[0m
[1;32m    280[0m         [0;32mif[0m [0mmode[0m [0;32min[0m [0;34m'ra'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 281[0;31m             [0mself[0m[0;34m.[0m[0m_read[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    282[0m [0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/scipy/io/netcdf.py[0m in [0;36m_read[0;34m(self)[0m
[1;32m    601[0m         [0;32mif[0m [0;32mnot[0m [0mmagic[0m [0;34m==[0m [0;34mb'CDF'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 602[0;31m             raise TypeError("Error: %s is not a valid NetCDF 3 file" %
[0m[1;32m    603[0m                             self.filename)

[0;31mTypeError[0m: Error: /home/runner/work/resources/resources/book/_static/data/rca/ctd/osb_ctd_jan2019_1min.nc is not a valid NetCDF 3 file

During handling of the above exception, another exception occurred:

[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-779868ffab58>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mosb_ctd_nc_file[0m [0;34m=[0m [0mdata_dir[0m [0;34m/[0m [0;34m"rca/ctd/osb_ctd_jan2019_1min.nc"[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mds_CTD[0m [0;34m=[0m [0mxr[0m[0;34m.[0m[0mopen_dataset[0m[0;34m([0m[0mosb_ctd_nc_file[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mds_CTD[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/xarray/backends/api.py[0m in [0;36mopen_dataset[0;34m(filename_or_obj, group, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, engine, chunks, lock, cache, drop_variables, backend_kwargs, use_cftime, decode_timedelta)[0m
[1;32m    555[0m [0;34m[0m[0m
[1;32m    556[0m     [0;32mwith[0m [0mclose_on_error[0m[0;34m([0m[0mstore[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 557[0;31m         [0mds[0m [0;34m=[0m [0mmaybe_decode_store[0m[0;34m([0m[0mstore[0m[0;34m,[0m [0mchunks[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    558[0m [0;34m[0m[0m
[1;32m    559[0m     [0;31m# Ensure source filename always stored in dataset object (GH issue #2550)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/xarray/backends/api.py[0m in [0;36mmaybe_decode_store[0;34m(store, chunks)[0m
[1;32m    451[0m [0;34m[0m[0m
[1;32m    452[0m     [0;32mdef[0m [0mmaybe_decode_store[0m[0;34m([0m[0mstore[0m[0;34m,[0m [0mchunks[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 453[0;31m         ds = conventions.decode_cf(
[0m[1;32m    454[0m             [0mstore[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    455[0m             [0mmask_and_scale[0m[0;34m=[0m[0mmask_and_scale[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/xarray/conventions.py[0m in [0;36mdecode_cf[0;34m(obj, concat_characters, mask_and_scale, decode_times, decode_coords, drop_variables, use_cftime, decode_timedelta)[0m
[1;32m    637[0m         [0mencoding[0m [0;34m=[0m [0mobj[0m[0;34m.[0m[0mencoding[0m[0;34m[0m[0;34m[0m[0m
[1;32m    638[0m     [0;32melif[0m [0misinstance[0m[0;34m([0m[0mobj[0m[0;34m,[0m [0mAbstractDataStore[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 639[0;31m         [0mvars[0m[0;34m,[0m [0mattrs[0m [0;34m=[0m [0mobj[0m[0;34m.[0m[0mload[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    640[0m         [0mextra_coords[0m [0;34m=[0m [0mset[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    641[0m         [0mclose[0m [0;34m=[0m [0mobj[0m[0;34m.[0m[0mclose[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/xarray/backends/common.py[0m in [0;36mload[0;34m(self)[0m
[1;32m    111[0m         """
[1;32m    112[0m         variables = FrozenDict(
[0;32m--> 113[0;31m             [0;34m([0m[0m_decode_variable_name[0m[0;34m([0m[0mk[0m[0;34m)[0m[0;34m,[0m [0mv[0m[0;34m)[0m [0;32mfor[0m [0mk[0m[0;34m,[0m [0mv[0m [0;32min[0m [0mself[0m[0;34m.[0m[0mget_variables[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mitems[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    114[0m         )
[1;32m    115[0m         [0mattributes[0m [0;34m=[0m [0mFrozenDict[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mget_attrs[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/xarray/backends/scipy_.py[0m in [0;36mget_variables[0;34m(self)[0m
[1;32m    164[0m     [0;32mdef[0m [0mget_variables[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    165[0m         return FrozenDict(
[0;32m--> 166[0;31m             [0;34m([0m[0mk[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mopen_store_variable[0m[0;34m([0m[0mk[0m[0;34m,[0m [0mv[0m[0;34m)[0m[0;34m)[0m [0;32mfor[0m [0mk[0m[0;34m,[0m [0mv[0m [0;32min[0m [0mself[0m[0;34m.[0m[0mds[0m[0;34m.[0m[0mvariables[0m[0;34m.[0m[0mitems[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    167[0m         )
[1;32m    168[0m [0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/xarray/backends/scipy_.py[0m in [0;36mds[0;34m(self)[0m
[1;32m    153[0m     [0;34m@[0m[0mproperty[0m[0;34m[0m[0;34m[0m[0m
[1;32m    154[0m     [0;32mdef[0m [0mds[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 155[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_manager[0m[0;34m.[0m[0macquire[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    156[0m [0;34m[0m[0m
[1;32m    157[0m     [0;32mdef[0m [0mopen_store_variable[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m,[0m [0mvar[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/xarray/backends/file_manager.py[0m in [0;36macquire[0;34m(self, needs_lock)[0m
[1;32m    179[0m             [0mAn[0m [0mopen[0m [0mfile[0m [0mobject[0m[0;34m,[0m [0;32mas[0m [0mreturned[0m [0mby[0m[0;31m [0m[0;31m`[0m[0;31m`[0m[0mopener[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;31m`[0m[0;31m`[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m    180[0m         """
[0;32m--> 181[0;31m         [0mfile[0m[0;34m,[0m [0m_[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_acquire_with_cache_info[0m[0;34m([0m[0mneeds_lock[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    182[0m         [0;32mreturn[0m [0mfile[0m[0;34m[0m[0;34m[0m[0m
[1;32m    183[0m [0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/xarray/backends/file_manager.py[0m in [0;36m_acquire_with_cache_info[0;34m(self, needs_lock)[0m
[1;32m    203[0m                     [0mkwargs[0m [0;34m=[0m [0mkwargs[0m[0;34m.[0m[0mcopy[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    204[0m                     [0mkwargs[0m[0;34m[[0m[0;34m"mode"[0m[0;34m][0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_mode[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 205[0;31m                 [0mfile[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_opener[0m[0;34m([0m[0;34m*[0m[0mself[0m[0;34m.[0m[0m_args[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    206[0m                 [0;32mif[0m [0mself[0m[0;34m.[0m[0m_mode[0m [0;34m==[0m [0;34m"w"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    207[0m                     [0;31m# ensure file doesn't get overriden when opened again[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/share/miniconda3/envs/cava-resources/lib/python3.8/site-packages/xarray/backends/scipy_.py[0m in [0;36m_open_scipy_netcdf[0;34m(filename, mode, mmap, version)[0m
[1;32m    103[0m             """
[1;32m    104[0m             [0merrmsg[0m [0;34m+=[0m [0mmsg[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 105[0;31m             [0;32mraise[0m [0mTypeError[0m[0;34m([0m[0merrmsg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    106[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    107[0m             [0;32mraise[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: Error: /home/runner/work/resources/resources/book/_static/data/rca/ctd/osb_ctd_jan2019_1min.nc is not a valid NetCDF 3 file
            If this is a NetCDF4 file, you may need to install the
            netcdf4 library, e.g.,

            $ pip install netcdf4
            
TypeError: Error: /home/runner/work/resources/resources/book/_static/data/rca/ctd/osb_ctd_jan2019_1min.nc is not a valid NetCDF 3 file
            If this is a NetCDF4 file, you may need to install the
            netcdf4 library, e.g.,

            $ pip install netcdf4
            

